.gitignore

For gems (libraries), dependency constraints belong in the gemspec.
Avoid locking dependencies to only a single version and instead allow
installation of any dependency within the supplied semantic range. This
helps ensure that the semantic range is indeed compatible with the gem.
When applications consume the gem, they will use their own Gemfile.lock
and lock both this gem and its dependencies.

Add Gemfile.lock to gitignore

---

bin/rails-response-dumper

Avoid leaking instance state from one dump method to the next. Each dump
method now starts with a fresh instance.

Instantiate the dumper class per dump_* method

---

.github/workflows/ci.yaml

It automatically runs bundle install and caches the result for faster
runs.
https://github.com/ruby/setup-ruby#caching-bundle-install-automatically

Use bundler-cache option in ruby/setup-ruby action

---

CHANGELOG.md
README.md
bin/rails-response-dumper

Sometimes after creating setup data, multiple responses should be dumped
to a file. For example, perhaps a series of JSON API calls are all
coupled to one another. Spreading these responses across multiple
methods can result in vastly different data in the output. Those
difference include randomly generated factory data and database IDs.
By dumping multiple responses, they always remain coupled.

Add support for dumping multiple responses per method

---

CHANGELOG.md
bin/rails-response-dumper

The modules inherited by ResponseDumper have many many methods. Avoid
the avalanche of useless text on the screen which hides the interesting
bits.

Override ResponseDumper#inspect

---

CHANGELOG.md
bin/rails-response-dumper

Provides methods `freeze_time`, `travel`, and `travel_to`.

Include ActiveSupport::Testing::TimeHelpers in ResponseDumper class

---

CHANGELOG.md
README.md
lib/rails_response_dumper/defined.rb
lib/rails_response_dumper/runner.rb
lib/response_dumper.rb

Dumpers are now defined with:
ResponseDumper.define 'Namespace::Controller' do
dump 'show' do
...
end
end
This syntax is heavily inspired b RSpec. The DSL is intended to result
in more readable dumpers and also reduce boilerplate. The dumped file
paths are also shorter as they no longer include the common class suffix
`_response_dumper` or the method prefix `dump_`.

Introduce a DSL

---

CHANGELOG.md
README.md
lib/rails_response_dumper/defined.rb
lib/rails_response_dumper/dump_block.rb
lib/rails_response_dumper/runner.rb
lib/response_dumper.rb

Removes the need to call expect_status_code! inside dump methods which
normally contain setup code and requests.

Make expected HTTP status code an argument to dump

---

lib/response_dumper.rb

Required for RSpec::Mocks::ExampleMethods.
Wasn't noticed before as it was implicitly loaded by the Rails
application.

Require 'rspec/mocks' in response_dumper.rb

---

bin/rails-response-dumper
lib/rails_response_dumper/runner.rb

Allow working with Rails applications that don't use ActiveRecord.
This was discovered when building a minimal Rails app -- which does not
include ActivedRecord -- to run RSpec with.

Make ActiveRecord optional

---

CHANGELOG.md
rails-response-dumper.gemspec

Fixes the following warning when building the gem:
WARNING:  open-ended dependency on rspec-mocks (>= 0) is not recommended
use a bounded requirement, such as '~> x.y'

Specify rspec-mocks version to fix warning

---

CHANGELOG.md
lib/rails_response_dumper/runner.rb
rails-response-dumper.gemspec

The mime/types package is used to parse the response content type. This
worked implicitly when the pakage was already loaded.
Make the relationship explicit in case the consuming Rails app does not
use it.

Declare mime/types as a dependency

---

.github/workflows/ci.yaml
.gitignore
Gemfile
spec/app/app/controllers/application_controller.rb
spec/app/app/controllers/root_controller.rb
spec/app/app/views/layouts/application.html.erb
spec/app/app/views/root/index.html
spec/app/config/application.rb
spec/app/config/boot.rb
spec/app/config/environment.rb
spec/app/config/environments/test.rb
spec/app/config/locales/en.yml
spec/app/config/routes.rb
spec/app/dumpers/root_response_dumper.rb
spec/app/snapshots/root/index/0.html
spec/cli_spec.rb
spec/spec_helper.rb
spec/support/matchers/match_snapshots.rb

https://relishapp.com/rspec
Add a very basic, minimal Rails app in the spec directory. The spec runs
the CLI on the Rails app and verifies the dumped output matches the
expected result.
The dumps are compared using "snapshots" inspired by Jest snapshot
testing. This ensures each run has byte-for-byte identical results.
https://jestjs.io/docs/snapshot-testing
With the ground work implemented, new tests can be added to fill in
coverage and new features can be accompanied by tests.

Add RSpec and a basic test

---

CHANGELOG.md
lib/rails_response_dumper/runner.rb
spec/cli_spec.rb
spec/test_apps/fail_app/app/controllers/application_controller.rb
spec/test_apps/fail_app/app/controllers/root_controller.rb
spec/test_apps/fail_app/app/views/layouts/application.html.erb
spec/test_apps/fail_app/app/views/root/index.html.erb
spec/test_apps/fail_app/config/application.rb
spec/test_apps/fail_app/config/boot.rb
spec/test_apps/fail_app/config/environment.rb
spec/test_apps/fail_app/config/environments/test.rb
spec/test_apps/fail_app/config/routes.rb
spec/test_apps/fail_app/dumpers/fail_app_dumper.rb

If an exception is hit during the dumping process, allow dumper
execution to complete, displaying all errors via stderr at end of
process execution.
Display the name and line number of failing dump block, as well as the
location of the exception.

Rescue errors to display after runner completes

---

CHANGELOG.md
lib/rails_response_dumper/runner.rb
spec/cli_spec.rb

Having all output go to a single stream allows testing feedback (both
the status line and the post-run error summary) to be piped to a single
location in a consistent manner.

Move output to stdout

---

CHANGELOG.md
README.md
lib/rails_response_dumper/runner.rb
spec/cli_spec.rb
spec/test_apps/app/app/controllers/tests_controller.rb
spec/test_apps/app/config/routes.rb
spec/test_apps/app/dumpers/tests_response_dumper.rb
spec/test_apps/app/snapshots/hooks/hook/0.json
spec/test_apps/app/snapshots/root/index/0.json
spec/test_apps/app/snapshots/tests/multiple_requests/0.json
spec/test_apps/app/snapshots/tests/post_with_body/0.json
spec/test_apps/app/snapshots/tests/post_with_body/1.json

The new format looks like:
{
"request": {
"method": "GET",
"url": "http://www.example.com/test",
"body": ""
},
"response": {
"status": 200,
"headers": {
"Content-Type": "text/html; charset=utf-8",
...
},
"body": "..."
}
}

Include the request body in the dump

---

CHANGELOG.md
README.md
lib/rails_response_dumper/runner.rb
spec/test_apps/app/snapshots/hooks/hook/0.json
spec/test_apps/app/snapshots/root/index/0.json
spec/test_apps/app/snapshots/tests/multiple_requests/0.json
spec/test_apps/app/snapshots/tests/multiple_requests/1.json
spec/test_apps/app/snapshots/tests/post_with_body/0.json
spec/test_apps/app/snapshots/tests/post_with_body/1.json

Can be used by consumers to create more representative mocked response data.

Include the response status code in the dump

---

CHANGELOG.md
bin/rails-response-dumper
lib/rails_response_dumper.rb
lib/rails_response_dumper/option_parser.rb
lib/rails_response_dumper/runner.rb
spec/cli_spec.rb

The option naming was inspired by rspec.
This option will abort rails-response-dumper after first error.
Without the flag it will capture all errors as usual.
e.g. `bundle exec rails-response-dumper --fail-fast`
fixes https://github.com/Pioneer-Valley-Books/rails-response-dumper/issues/55

Add --fail-fast cli option

---

CHANGELOG.md
lib/rails_response_dumper/runner.rb
spec/cli_spec.rb
spec/test_apps/fail_app/dumpers/fail_app_dumper_2.rb

The first implementation was only breaking early out of the loop that iterated through a single dumper's dumps.
However, it would then move on to the next dumper as usual.
This update will exit both loops and correctly abort after first failure.
Added a second dumper to the fail_app specs to verify this was working correctly.

Fix --fail-fast option

---

lib/rails_response_dumper/option_parser.rb
lib/rails_response_dumper/runner.rb
spec/cli_spec.rb

This option will print the dumper and dump block names.
e.g. `bundle exec rails-response-dumper --verbose`

Add --verbose cli option

---

CHANGELOG.md
lib/rails_response_dumper/option_parser.rb
lib/rails_response_dumper/runner.rb
spec/cli_spec.rb

The option naming was inspired by rspec.
`--order random` will run the dumps in a random order.
If given a seed value e.g. `--order 8` it will initialize the pseudo random number generator with the provided seed value to run the dumps in a reproducible order.
fixes #60

Add --order CLI option

---

CHANGELOG.md
lib/rails_response_dumper/option_parser.rb
lib/rails_response_dumper/runner.rb
rails-response-dumper.gemspec
spec/cli_spec.rb
spec/support/matchers/match_snapshots.rb
spec/test_apps/app/snapshots_without_response_headers/hooks/hook/0.json
spec/test_apps/app/snapshots_without_response_headers/root/index/0.json
spec/test_apps/app/snapshots_without_response_headers/tests/multiple_requests/0.json
spec/test_apps/app/snapshots_without_response_headers/tests/multiple_requests/1.json
spec/test_apps/app/snapshots_without_response_headers/tests/post_with_body/0.json
spec/test_apps/app/snapshots_without_response_headers/tests/post_with_body/1.json

Add CLI option to exclude response headers.
Response headers could make response dumper output nondeterministic.  
To help with test environments that do not require response headers the CLI option
can now be used to filter out the extra content.
The snapshot test helper was updated to allow for optionally specifying a non standard
snapshot directory to help test both including and excluding response headers on the
test app.

Add CLI option to exclude response headers

---

CHANGELOG.md
Gemfile
lib/rails_response_dumper/runner.rb
spec/cli_spec.rb
spec/test_apps/.rubocop.yml
spec/test_apps/app/Rakefile
spec/test_apps/app/app/controllers/books_controller.rb
spec/test_apps/app/app/models/application_record.rb
spec/test_apps/app/app/models/book.rb
spec/test_apps/app/bin/rails
spec/test_apps/app/config/application.rb
spec/test_apps/app/config/routes.rb
spec/test_apps/app/db/migrate/0000_create_books.rb
spec/test_apps/app/db/schema.rb
spec/test_apps/app/dumpers/books_response_dumper.rb
spec/test_apps/app/snapshots/books/create/0.json
spec/test_apps/app/snapshots_updated_dump/books/create/0.json
spec/test_apps/app/snapshots_without_response_headers/books/create/0.json

In order for model after_commit hooks to execute, the first transaction must be started with `joinable: false`. This is the strategy used by Rails test classes.
This is especially important for use with ActiveStorage which uses the after_commit hook to upload the file to the service.

Start database transaction with `joinable: false` argument

---

CHANGELOG.md
lib/rails_response_dumper/option_parser.rb
lib/rails_response_dumper/runner.rb
lib/response_dumper.rb
spec/cli_spec.rb

Its value is the Rails timestamp in ISO 8601 format.
This value could be used to stub or fake the system time to better match the environment of that generated the dump.

Add `timestamp` property to dumps

---

spec/test_apps/app/snapshots/books/create/0.json
spec/test_apps/app/snapshots/hooks/hook/0.json
spec/test_apps/app/snapshots/root/index/0.json
spec/test_apps/app/snapshots/tests/multiple_requests/0.json
spec/test_apps/app/snapshots/tests/multiple_requests/1.json
spec/test_apps/app/snapshots/tests/post_with_body/0.json
spec/test_apps/app/snapshots/tests/post_with_body/1.json
spec/test_apps/app/snapshots_single_file/tests/multiple_requests/0.json
spec/test_apps/app/snapshots_single_file/tests/multiple_requests/1.json
spec/test_apps/app/snapshots_single_file/tests/post_with_body/0.json
spec/test_apps/app/snapshots_single_file/tests/post_with_body/1.json
spec/test_apps/app/snapshots_two_files/root/index/0.json
spec/test_apps/app/snapshots_two_files/tests/multiple_requests/0.json
spec/test_apps/app/snapshots_two_files/tests/multiple_requests/1.json
spec/test_apps/app/snapshots_two_files/tests/post_with_body/0.json
spec/test_apps/app/snapshots_two_files/tests/post_with_body/1.json
spec/test_apps/app/snapshots_updated_dump/books/create/0.json
spec/test_apps/app/snapshots_updated_dump/hooks/hook/0.json
spec/test_apps/app/snapshots_updated_dump/root/index/0.json
spec/test_apps/app/snapshots_updated_dump/tests/another_post/0.json
spec/test_apps/app/snapshots_updated_dump/tests/post_with_body/0.json
spec/test_apps/app/snapshots_updated_dump/tests/post_with_body/1.json

Rack now lowercases all header names. See the changelog:
https://github.com/rack/rack/blob/main/CHANGELOG.md
> Response header keys can no longer include uppercase characters.
> Rack::Headers added to support lower-case header keys.

Update snapshots to match Rack 3

---

spec/cli_spec.rb

Tweak tests on `stdout` so they don't count '.'s, but rather expect any nonzero
number of them, so they don't need to be updated with every new test dumper.
The count and important outputs are already being tested.

Remove excess checks on dumper count

---

CHANGELOG.md
README.md
bin/rails-response-dumper
lib/rails_response_dumper.rb
lib/response_dumper.rb
spec/test_apps/after_hook/dumpers/dumpers_helper.rb
spec/test_apps/app/dumpers/dumpers_helper.rb
spec/test_apps/fail_app/dumpers/dumpers_helper.rb

By allowing the application to load Rails configuration, the application can run other code necessary to setup the environment. For example, the application could enable coverage tools.

Allow the application to load Rails configuration

---

Gemfile

Currently there is an issue when attempting to use the latest version of `sqlite3` because it was pinned to version 1.4. An upstream fix has landed on main, but has not been released yet.
Error observed:
```
Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.1-arm64-darwin. Make sure all dependencies are added to Gemfile. (LoadError)
```
Upstream Fix: https://github.com/rails/rails/commit/e90cb82384b3709186ace6465543785fcd348f0a
Target Release (7.2): https://github.com/rails/rails/blob/7-2-stable/activerecord/CHANGELOG.md
Once 7.2 is released, `sqlite3` should be allowed to take the latest version.

Pin `sqlite3` to `1.X`

---

CHANGELOG.md
lib/rails_response_dumper/runner.rb
spec/test_apps/app/snapshots/hooks/hook/0.json
spec/test_apps/app/snapshots/root/index/0.json
spec/test_apps/app/snapshots/tests/multiple_requests/0.json
spec/test_apps/app/snapshots_single_file/tests/multiple_requests/0.json
spec/test_apps/app/snapshots_two_files/root/index/0.json
spec/test_apps/app/snapshots_two_files/tests/multiple_requests/0.json
spec/test_apps/app/snapshots_updated_dump/hooks/hook/0.json
spec/test_apps/app/snapshots_updated_dump/root/index/0.json
spec/test_apps/app/snapshots_without_response_headers/hooks/hook/0.json
spec/test_apps/app/snapshots_without_response_headers/root/index/0.json
spec/test_apps/app/snapshots_without_response_headers/tests/multiple_requests/0.json

Starting with Rack 3.1, rack.input is optional which results in request.body being nil.
See:
https://github.com/rack/rack/blob/main/CHANGELOG.md
> SPEC Changes
>
> rack.input is now optional.

Make compatible with Rack 3.1

---

rails-response-dumper.gemspec

The "add_runtime_dependency" alias is soft-deprecated in favor of add_dependency. Fixes RuboCop offense:
```
rails-response-dumper.gemspec:22:8: C: [Correctable] Gemspec/AddRuntimeDependency: Use add_dependency instead of add_runtime_dependency.
spec.add_runtime_dependency 'rails', '>= 6.1', '< 8'
^^^^^^^^^^^^^^^^^^^^^^
rails-response-dumper.gemspec:23:8: C: [Correctable] Gemspec/AddRuntimeDependency: Use add_dependency instead of add_runtime_dependency.
spec.add_runtime_dependency 'rspec-mocks', '~> 3.0'
^^^^^^^^^^^^^^^^^^^^^^
```

Change gemspec to use "add_dependency"

---

Gemfile

Since the release of Rails 7.2, the latest version of sqlite3 is supported.
Rails 7.2 was released August 10, 2024. See the announcement: https://rubyonrails.org/2024/8/10/Rails-7-2-0-has-been-released

Remove sqlite3 pinned version from Gemfile

---

rails-response-dumper.gemspec

Allow projects using rails-response-dumpers to update Rails and other dependencies without being blocked by this as a dependency.

Remove upper bound from dependencies
